package pt.ipleiria.estg.dei.vetgestlink.model;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

import java.util.ArrayList;

public class NotaBDHelper extends SQLiteOpenHelper {

    private static final String BD_NOME = "vetgestlink";
    private static final int BD_VERSION = 1;
    private static final String TABELA_NOME = "notas";

    private final String ID = "id";
    private final String NOTA = "nota";
    private final String CREATED_AT = "created_at";
    private final String USERPROFILES_ID = "userprofiles_id";
    private final String ANIMAIS_ID = "animais_id";

    private final SQLiteDatabase bd;

    public NotaBDHelper(@Nullable Context context) {
        super(context, BD_NOME, null, BD_VERSION);
        this.bd = getWritableDatabase();
    }

    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {
        String createTable = "CREATE TABLE " + TABELA_NOME + " (" +
                ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
                NOTA + " TEXT NOT NULL, " +
                CREATED_AT + " TEXT NOT NULL, " +
                USERPROFILES_ID + " INTEGER NOT NULL, " +
                ANIMAIS_ID + " INTEGER NOT NULL" +
                ");";

        sqLiteDatabase.execSQL(createTable);
    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int oldVersion, int newVersion) {
        sqLiteDatabase.execSQL("DROP TABLE IF EXISTS " + TABELA_NOME);
        this.onCreate(sqLiteDatabase);
    }

    // -------------------------------
    // CRUD operations
    // -------------------------------

    public Nota adicionarNotaBD(Nota nota) {
        ContentValues values = new ContentValues();
        values.put(NOTA, nota.getNota());
        values.put(CREATED_AT, nota.getCreatedAt());
        values.put(USERPROFILES_ID, nota.getUserprofilesId());
        values.put(ANIMAIS_ID, nota.getAnimaisId());

        long id = this.bd.insert(TABELA_NOME, null, values);
        if (id > -1) {
            nota.setId((int) id);  // set the autogenerated id
            return nota;
        }
        return null;
    }

    public boolean editarNotaBD(Nota nota) {
        ContentValues values = new ContentValues();
        values.put(NOTA, nota.getNota());
        values.put(CREATED_AT, nota.getCreatedAt());
        values.put(USERPROFILES_ID, nota.getUserprofilesId());
        values.put(ANIMAIS_ID, nota.getAnimaisId());

        int numLinhas = this.bd.update(TABELA_NOME, values, ID + "=?", new String[]{String.valueOf(nota.getId())});
        return numLinhas > 0;
    }

    public boolean removerNotaBD(int id) {
        int numLinhas = this.bd.delete(TABELA_NOME, ID + "=?", new String[]{String.valueOf(id)});
        return numLinhas > 0;
    }

    public void removerAllNotasBD() {
        this.bd.delete(TABELA_NOME, null, null);
    }

    public ArrayList<Nota> getAllNotasBD() {
        ArrayList<Nota> notas = new ArrayList<>();
        Cursor cursor = this.bd.query(TABELA_NOME,
                new String[]{ID, NOTA, CREATED_AT, USERPROFILES_ID, ANIMAIS_ID},
                null, null, null, null,
                CREATED_AT + " DESC");

        if (cursor.moveToFirst()) {
            do {
                Nota auxNota = new Nota(
                        cursor.getInt(0),
                        cursor.getString(1),
                        cursor.getString(2)
                );
                auxNota.setUserprofilesId(cursor.getInt(3));
                auxNota.setAnimaisId(cursor.getInt(4));

                notas.add(auxNota);
            } while (cursor.moveToNext());
        }
        cursor.close();
        return notas;
    }
}
